create table if not exists public.gx_assignments (
  assignment_code text primary key,
  title text not null,
  class_code text not null,
  mode text not null,
  route text,
  question_count integer not null default 5 check (question_count between 1 and 50),
  time_limit_minutes integer not null default 20 check (time_limit_minutes between 1 and 180),
  deadline timestamptz,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.gx_assignment_submissions (
  id bigint generated by default as identity primary key,
  assignment_code text not null references public.gx_assignments(assignment_code) on delete cascade,
  class_code text not null,
  student_name text not null,
  score numeric not null default 0,
  max_score numeric not null default 0,
  percentage numeric not null default 0 check (percentage between 0 and 100),
  status text not null default 'completed' check (status in ('started','completed','late')),
  wrong_topics jsonb not null default '[]'::jsonb,
  started_at timestamptz,
  completed_at timestamptz not null default now(),
  duration_seconds integer not null default 0,
  unique (assignment_code, student_name)
);

create index if not exists gx_assignments_class_idx on public.gx_assignments(class_code, created_at desc);
create index if not exists gx_assignment_submissions_idx on public.gx_assignment_submissions(assignment_code, percentage desc, completed_at asc);

alter table public.gx_assignments enable row level security;
alter table public.gx_assignment_submissions enable row level security;

drop policy if exists gx_assignments_read on public.gx_assignments;
create policy gx_assignments_read on public.gx_assignments for select using (true);
drop policy if exists gx_assignments_insert on public.gx_assignments;
create policy gx_assignments_insert on public.gx_assignments for insert with check (true);
drop policy if exists gx_assignments_update on public.gx_assignments;
create policy gx_assignments_update on public.gx_assignments for update using (true) with check (true);

drop policy if exists gx_submissions_read on public.gx_assignment_submissions;
create policy gx_submissions_read on public.gx_assignment_submissions for select using (true);
drop policy if exists gx_submissions_insert on public.gx_assignment_submissions;
create policy gx_submissions_insert on public.gx_assignment_submissions for insert with check (true);
drop policy if exists gx_submissions_update on public.gx_assignment_submissions;
create policy gx_submissions_update on public.gx_assignment_submissions for update using (true) with check (true);

alter publication supabase_realtime add table public.gx_assignments;
alter publication supabase_realtime add table public.gx_assignment_submissions;