-- GX Sejarah V2.1 cross-device class boss schema
-- Run in Supabase SQL Editor.

create table if not exists public.gx_class_boss_rooms (
  class_code text primary key,
  boss_hp integer not null default 1000,
  boss_max_hp integer not null default 1000,
  class_hp integer not null default 500,
  class_max_hp integer not null default 500,
  phase integer not null default 1,
  status text not null default 'active',
  total_damage integer not null default 0,
  total_heal integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.gx_class_boss_players (
  id bigint generated by default as identity primary key,
  class_code text not null references public.gx_class_boss_rooms(class_code) on delete cascade,
  student_name text not null,
  damage integer not null default 0,
  correct_count integer not null default 0,
  wrong_count integer not null default 0,
  last_seen timestamptz not null default now(),
  unique(class_code, student_name)
);

create table if not exists public.gx_class_boss_actions (
  id bigint generated by default as identity primary key,
  class_code text not null,
  student_name text not null,
  question_id text,
  is_correct boolean not null,
  damage integer not null default 0,
  boss_heal integer not null default 0,
  class_damage integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.gx_class_boss_rooms enable row level security;
alter table public.gx_class_boss_players enable row level security;
alter table public.gx_class_boss_actions enable row level security;

create policy "anon read rooms" on public.gx_class_boss_rooms for select to anon using (true);
create policy "anon insert rooms" on public.gx_class_boss_rooms for insert to anon with check (char_length(class_code) between 3 and 12);
create policy "anon update rooms" on public.gx_class_boss_rooms for update to anon using (true) with check (boss_hp between 0 and boss_max_hp and class_hp between 0 and class_max_hp);

create policy "anon read players" on public.gx_class_boss_players for select to anon using (true);
create policy "anon insert players" on public.gx_class_boss_players for insert to anon with check (char_length(student_name) between 1 and 40);
create policy "anon update players" on public.gx_class_boss_players for update to anon using (true) with check (damage >= 0 and correct_count >= 0 and wrong_count >= 0);

create policy "anon read actions" on public.gx_class_boss_actions for select to anon using (true);
create policy "anon insert actions" on public.gx_class_boss_actions for insert to anon with check (char_length(student_name) between 1 and 40);

create index if not exists gx_class_boss_players_room_idx on public.gx_class_boss_players(class_code, damage desc);
create index if not exists gx_class_boss_actions_room_idx on public.gx_class_boss_actions(class_code, created_at desc);

alter publication supabase_realtime add table public.gx_class_boss_rooms;
alter publication supabase_realtime add table public.gx_class_boss_players;
alter publication supabase_realtime add table public.gx_class_boss_actions;
