-- GX Sejarah V0.5 Supabase schema
-- Run this in Supabase SQL Editor.

create table if not exists public.gx_sejarah_scores (
  id bigint generated by default as identity primary key,
  student_name text not null,
  class_code text not null,
  world_id text not null default 'world-1',
  score integer not null default 0,
  max_score integer not null default 0,
  correct_count integer not null default 0,
  wrong_count integer not null default 0,
  hint_count integer not null default 0,
  progress_percent integer not null default 0,
  wrong_topics jsonb not null default '[]'::jsonb,
  status text not null default 'completed',
  session_id text not null,
  created_at timestamptz not null default now()
);

create index if not exists gx_sejarah_scores_class_code_idx
  on public.gx_sejarah_scores (class_code, created_at desc);

create index if not exists gx_sejarah_scores_student_idx
  on public.gx_sejarah_scores (student_name, class_code);

alter table public.gx_sejarah_scores enable row level security;

-- Students may submit scores using the public anon key.
create policy "public can insert scores"
on public.gx_sejarah_scores
for insert
to anon
with check (
  char_length(student_name) between 1 and 40
  and char_length(class_code) between 3 and 12
  and score >= 0
  and max_score >= 0
  and correct_count >= 0
  and wrong_count >= 0
  and hint_count >= 0
  and progress_percent between 0 and 100
);

-- Demo dashboard read policy. For production, replace this with teacher authentication.
create policy "public can read class scores"
on public.gx_sejarah_scores
for select
to anon
using (true);

-- Optional realtime support
alter publication supabase_realtime add table public.gx_sejarah_scores;
