-- GX Sejarah V2.5 cross-device weekly league
create table if not exists public.gx_weekly_league_scores (
  id bigint generated by default as identity primary key,
  week_key text not null,
  class_code text not null,
  student_name text not null,
  score integer not null default 0 check (score >= 0 and score <= 10),
  correct_count integer not null default 0 check (correct_count >= 0 and correct_count <= 10),
  wrong_count integer not null default 0 check (wrong_count >= 0 and wrong_count <= 10),
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  xp_awarded integer not null default 0 check (xp_awarded >= 0),
  submitted_at timestamptz not null default now(),
  unique (week_key, class_code, student_name)
);

alter table public.gx_weekly_league_scores enable row level security;

drop policy if exists "weekly league public read" on public.gx_weekly_league_scores;
create policy "weekly league public read"
on public.gx_weekly_league_scores for select
to anon, authenticated
using (true);

drop policy if exists "weekly league public insert" on public.gx_weekly_league_scores;
create policy "weekly league public insert"
on public.gx_weekly_league_scores for insert
to anon, authenticated
with check (
  char_length(class_code) between 2 and 20
  and char_length(student_name) between 1 and 40
  and score between 0 and 10
);

drop policy if exists "weekly league public update" on public.gx_weekly_league_scores;
create policy "weekly league public update"
on public.gx_weekly_league_scores for update
to anon, authenticated
using (true)
with check (
  char_length(class_code) between 2 and 20
  and char_length(student_name) between 1 and 40
  and score between 0 and 10
);

create index if not exists gx_weekly_league_lookup_idx
on public.gx_weekly_league_scores (week_key, class_code, score desc, duration_seconds asc);

alter publication supabase_realtime add table public.gx_weekly_league_scores;
