window.PHASE2_WORLD4 = [
{ id:'JA-001',cat:'Jenis Ayat',skill:'Ayat penyata biasa',difficulty:'Sederhana Tinggi',q:'Pihak sekolah akan mengadakan latihan kebakaran pada minggu hadapan.',i:'Nyatakan jenis ayat.',a:['Ayat penyata','Ayat tanya','Ayat perintah','Ayat seruan'],c:0,e:'Ayat ini menyampaikan maklumat tentang tindakan pihak sekolah tanpa meminta jawapan atau memberi arahan.',cn:'这句话只是说明学校下周将进行消防演习，没有提问、命令或感叹，所以是陈述句。',formula:'Memberi maklumat = Ayat penyata.',mnemonic:'只是告诉你一件事，就是 Penyata。',trap:'Menganggap semua ayat yang mengandungi kata “akan” ialah ayat perintah.',keywords:['akan mengadakan','minggu hadapan'] },
{ id:'JA-002',cat:'Jenis Ayat',skill:'Ayat tanya dengan kata tanya',difficulty:'Sederhana Tinggi',q:'Siapakah yang mengetuai pasukan debat sekolah kita tahun ini?',i:'Tentukan jenis ayat.',a:['Ayat penyata','Ayat tanya','Ayat perintah','Ayat seruan'],c:1,e:'Kata tanya “siapakah” digunakan untuk mendapatkan jawapan tentang orang.',cn:'“Siapakah”是在问“是谁”，句子要求别人回答，所以是疑问句。',formula:'Ada kata tanya dan memerlukan jawapan = Ayat tanya.',mnemonic:'看到 siapa、apa、bila、mengapa，先想 Tanya。',trap:'Terpengaruh oleh bentuk panjang ayat lalu memilih penyata.',keywords:['siapakah','?'] },
{ id:'JA-003',cat:'Jenis Ayat',skill:'Ayat perintah larangan',difficulty:'Sederhana Tinggi',q:'Jangan sesekali memasuki makmal tanpa kebenaran guru.',i:'Nyatakan jenis ayat.',a:['Ayat penyata','Ayat tanya','Ayat perintah','Ayat seruan'],c:2,e:'Kata “jangan” menunjukkan larangan, iaitu salah satu bentuk ayat perintah.',cn:'“Jangan”表示禁止别人做某事，因此属于祈使句。',formula:'Jangan / usah = larangan = Ayat perintah.',mnemonic:'Jangan、usah 一出现，多数就是 Perintah。',trap:'Menganggap ayat tanpa tanda seru bukan ayat perintah.',keywords:['jangan','tanpa kebenaran'] },
{ id:'JA-004',cat:'Jenis Ayat',skill:'Ayat seruan dengan kata seru',difficulty:'Sederhana Tinggi',q:'Wah, hebat benar persembahan teater para pelajar itu!',i:'Tentukan jenis ayat.',a:['Ayat penyata','Ayat tanya','Ayat perintah','Ayat seruan'],c:3,e:'Kata seru “wah” menyatakan perasaan kagum yang kuat.',cn:'“Wah”表达强烈的赞叹感情，所以是感叹句。',formula:'Kata seru + perasaan kuat = Ayat seruan.',mnemonic:'Wah、aduh、amboi 加强烈感情，就是 Seruan。',trap:'Hanya melihat isi maklumat lalu memilih penyata.',keywords:['wah','!'] },
{ id:'JA-005',cat:'Jenis Ayat',skill:'Ayat tanya tanpa kata tanya',difficulty:'Sukar',q:'Adakah semua ahli kumpulan telah memahami arahan tersebut?',i:'Nyatakan jenis ayat.',a:['Ayat penyata','Ayat tanya','Ayat perintah','Ayat seruan'],c:1,e:'Kata “adakah” membentuk soalan yang memerlukan jawapan ya atau tidak.',cn:'“Adakah”用来提出是非问题，需要回答“是或不是”，所以是疑问句。',formula:'Adakah / apakah + jawapan ya atau tidak = Ayat tanya.',mnemonic:'看到 adakah，就是在等答案。',trap:'Menganggap ayat yang lengkap dan formal sebagai penyata.',keywords:['adakah','?'] },
{ id:'JA-006',cat:'Jenis Ayat',skill:'Ayat perintah permintaan',difficulty:'Sukar',q:'Tolong serahkan borang penyertaan ini kepada guru penasihat sebelum waktu rehat.',i:'Tentukan jenis ayat.',a:['Ayat penyata','Ayat tanya','Ayat perintah','Ayat seruan'],c:2,e:'Kata “tolong” menunjukkan permintaan yang masih tergolong dalam ayat perintah.',cn:'“Tolong”虽然语气礼貌，但仍是在请求别人做事，所以属于祈使句。',formula:'Tolong / sila / harap = permintaan atau arahan = Ayat perintah.',mnemonic:'礼貌请求也还是 Perintah。',trap:'Menganggap ayat sopan tidak boleh menjadi ayat perintah.',keywords:['tolong','serahkan'] },
{ id:'JA-007',cat:'Jenis Ayat',skill:'Ayat seruan tanpa kata seru awal',difficulty:'Sukar',q:'Cantiknya pemandangan dari puncak bukit itu!',i:'Nyatakan jenis ayat.',a:['Ayat penyata','Ayat tanya','Ayat perintah','Ayat seruan'],c:3,e:'Bentuk “cantiknya” dan tanda seru menunjukkan perasaan kagum yang kuat walaupun tiada kata seru seperti “wah”.',cn:'即使没有“wah”，句子仍表达强烈赞叹，而且以感叹号结尾，所以是感叹句。',formula:'Perasaan kuat + tanda seru boleh membentuk Ayat seruan.',mnemonic:'没有 wah 也没关系，强烈感情就是 Seruan。',trap:'Mesti mencari kata seru di awal ayat sebelum memilih seruan.',keywords:['cantiknya','!'] },
{ id:'JA-008',cat:'Jenis Ayat',skill:'Ayat penyata negatif',difficulty:'Sukar',q:'Sebahagian peserta belum menyerahkan laporan lengkap kepada pihak urus setia.',i:'Tentukan jenis ayat.',a:['Ayat penyata','Ayat tanya','Ayat perintah','Ayat seruan'],c:0,e:'Walaupun mengandungi kata negatif “belum”, ayat ini hanya menyampaikan maklumat.',cn:'虽然有“belum”，但句子只是说明部分参赛者还未交报告，所以仍是陈述句。',formula:'Lihat tujuan ayat, bukan kata negatif semata-mata.',mnemonic:'不是看到 belum、tidak 就改变句子种类。',trap:'Menyangka kata negatif menjadikan ayat perintah atau tanya.',keywords:['belum','menyerahkan'] },
{ id:'JA-009',cat:'Jenis Ayat',skill:'Ayat tanya sebab',difficulty:'Sukar',q:'Mengapakah beberapa orang peserta masih belum mendaftarkan diri?',i:'Nyatakan jenis ayat.',a:['Ayat penyata','Ayat tanya','Ayat perintah','Ayat seruan'],c:1,e:'Kata tanya “mengapakah” meminta sebab atau alasan.',cn:'“Mengapakah”是在问原因，因此是疑问句。',formula:'Mengapa / mengapakah = bertanya sebab = Ayat tanya.',mnemonic:'问“为什么”，一定是 Tanya。',trap:'Terpengaruh oleh kata “belum” lalu fokus pada maklumat negatif.',keywords:['mengapakah','?'] },
{ id:'JA-010',cat:'Jenis Ayat',skill:'Ayat perintah silaan',difficulty:'Sukar',q:'Silalah masuk ke dalam dewan dan duduk di tempat yang telah disediakan.',i:'Tentukan jenis ayat.',a:['Ayat penyata','Ayat tanya','Ayat perintah','Ayat seruan'],c:2,e:'Kata “silalah” menunjukkan pelawaan atau silaan, salah satu bentuk ayat perintah.',cn:'“Silalah”表示邀请或请对方做某事，属于祈使句。',formula:'Sila / silalah = silaan = Ayat perintah.',mnemonic:'邀请别人做，也属于 Perintah。',trap:'Menganggap pelawaan sebagai ayat penyata kerana nadanya lembut.',keywords:['silalah','masuk'] },
{ id:'JA-011',cat:'Jenis Ayat',skill:'Ayat seruan kesakitan',difficulty:'Sederhana Tinggi',q:'Aduh, sakitnya kaki saya selepas latihan yang panjang itu!',i:'Nyatakan jenis ayat.',a:['Ayat penyata','Ayat tanya','Ayat perintah','Ayat seruan'],c:3,e:'Kata seru “aduh” menyatakan kesakitan dan emosi yang kuat.',cn:'“Aduh”表达疼痛和强烈感受，所以是感叹句。',formula:'Aduh + kesakitan = Ayat seruan.',mnemonic:'Aduh 是痛，直接想到 Seruan。',trap:'Fokus pada maklumat tentang kaki lalu memilih penyata.',keywords:['aduh','sakitnya'] },
{ id:'JA-012',cat:'Jenis Ayat',skill:'Ayat penyata dengan kata adjektif',difficulty:'Sukar',q:'Keadaan jalan menuju ke perkampungan itu semakin berbahaya selepas hujan lebat.',i:'Tentukan jenis ayat.',a:['Ayat penyata','Ayat tanya','Ayat perintah','Ayat seruan'],c:0,e:'Ayat ini menerangkan keadaan jalan dan tidak menunjukkan pertanyaan, arahan atau seruan.',cn:'句子只是说明道路越来越危险，没有要求回答或行动，所以是陈述句。',formula:'Penerangan keadaan = Ayat penyata.',mnemonic:'说明状况，不等于感叹。',trap:'Menganggap kata adjektif “berbahaya” menjadikan ayat seruan.',keywords:['semakin berbahaya','selepas hujan'] },
{ id:'JA-013',cat:'Jenis Ayat',skill:'Ayat perintah tegahan halus',difficulty:'Sukar',q:'Usah kamu sebarkan khabar yang belum dipastikan kesahihannya.',i:'Nyatakan jenis ayat.',a:['Ayat penyata','Ayat tanya','Ayat perintah','Ayat seruan'],c:2,e:'Kata “usah” membawa maksud larangan atau tegahan.',cn:'“Usah”表示不要做某事，是禁止性质的祈使句。',formula:'Usah = jangan = larangan = Ayat perintah.',mnemonic:'Usah 就是 jangan 的兄弟。',trap:'Menganggap “usah” sebagai kata biasa dan memilih penyata.',keywords:['usah','sebarkan'] },
{ id:'JA-014',cat:'Jenis Ayat',skill:'Ayat tanya pilihan',difficulty:'Sukar',q:'Kamu mahu menyertai pertandingan pidato atau pertandingan bahas?',i:'Tentukan jenis ayat.',a:['Ayat penyata','Ayat tanya','Ayat perintah','Ayat seruan'],c:1,e:'Ayat ini meminta pendengar memilih antara dua pilihan.',cn:'句子要求对方在演讲比赛和辩论比赛之间作选择，因此是疑问句。',formula:'Soalan pilihan biasanya menggunakan “atau”.',mnemonic:'要你二选一，就是 Tanya。',trap:'Melihat kata “mahu” lalu menyangka ayat penyata.',keywords:['atau','?'] },
{ id:'JA-015',cat:'Jenis Ayat',skill:'Analisis tujuan ayat kompleks',difficulty:'Sangat Sukar',q:'Betapa bangganya kami apabila pasukan sekolah diumumkan sebagai juara kebangsaan!',i:'Nyatakan jenis ayat.',a:['Ayat penyata','Ayat tanya','Ayat perintah','Ayat seruan'],c:3,e:'Kata “betapa” dan bentuk “bangganya” menegaskan perasaan bangga yang sangat kuat.',cn:'“Betapa bangganya”强调非常强烈的自豪感，所以是感叹句。',formula:'Betapa + perasaan = Ayat seruan.',mnemonic:'Betapa 一出现，先检查是不是强烈感情。',trap:'Ayat panjang dan mengandungi maklumat tidak semestinya penyata.',keywords:['betapa','bangganya','!'] }
];