window.PHASE2_WORLD3 = [
{
 id:'PA-001',cat:'Pola Ayat',skill:'FN + FN dengan predikat frasa nama',difficulty:'Sederhana Tinggi',
 q:'Lelaki yang sedang berbual dengan pengetua itu abang kepada rakan sekelas saya.',
 i:'Tentukan pola ayat dasar yang tepat.',
 a:['FN + FN','FN + FK','FN + FA','FN + FS'],c:0,
 e:'Subjek ialah frasa nama “Lelaki yang sedang berbual dengan pengetua itu”. Predikat “abang kepada rakan sekelas saya” juga frasa nama.',
 cn:'主语是名词短语；谓语“是我同学的哥哥”也是名词短语，所以是 FN + FN。',
 formula:'Lihat inti predikat: nama orang/benda/jawatan = FN.',
 mnemonic:'谓语在说明“他是谁”＝FN。',
 trap:'Melihat kata “sedang berbual” dalam subjek lalu terus memilih FN + FK.',
 keywords:['abang kepada','predikat frasa nama']
},
{
 id:'PA-002',cat:'Pola Ayat',skill:'FN + FK dengan kata bantu aspek',difficulty:'Sederhana Tinggi',
 q:'Para peserta bengkel itu sedang menyiapkan tugasan berkumpulan.',
 i:'Pilih pola ayat dasar.',
 a:['FN + FN','FN + FK','FN + FA','FN + FS'],c:1,
 e:'Predikat “sedang menyiapkan tugasan berkumpulan” berinti kata kerja “menyiapkan”.',
 cn:'谓语核心是动作“完成”，所以属于 Frasa Kerja，答案是 FN + FK。',
 formula:'Kata bantu + kata kerja masih dikira FK.',
 mnemonic:'看到动作核心，就选 FK。',
 trap:'Menganggap kata “sedang” menentukan pola.',
 keywords:['sedang menyiapkan','kata kerja']
},
{
 id:'PA-003',cat:'Pola Ayat',skill:'FN + FA dengan penguat',difficulty:'Sederhana Tinggi',
 q:'Pemandangan dari puncak bukit tersebut sungguh menakjubkan.',
 i:'Tentukan pola ayat dasar.',
 a:['FN + FN','FN + FK','FN + FA','FN + FS'],c:2,
 e:'Predikat “sungguh menakjubkan” menerangkan sifat pemandangan dan berinti kata adjektif.',
 cn:'“非常壮观”是在说明景色的性质，所以是 Frasa Adjektif，答案 FN + FA。',
 formula:'Penguat seperti sangat, amat, sungguh + sifat = FA.',
 mnemonic:'很、非常、十分＋性质＝FA。',
 trap:'Menganggap “menakjubkan” sebagai kata kerja kerana bentuknya panjang.',
 keywords:['sungguh','menakjubkan']
},
{
 id:'PA-004',cat:'Pola Ayat',skill:'FN + FS sebagai lokasi',difficulty:'Sederhana Tinggi',
 q:'Semua dokumen sulit itu di dalam kabinet berkunci.',
 i:'Pilih pola ayat dasar.',
 a:['FN + FN','FN + FK','FN + FA','FN + FS'],c:3,
 e:'Predikat bermula dengan kata sendi nama “di” dan menerangkan lokasi.',
 cn:'谓语以介词“di”开头，并说明地点，所以是 Frasa Sendi Nama。',
 formula:'Predikat bermula dengan di/ke/dari/untuk/kepada = FS.',
 mnemonic:'谓语一开头就是介词，多数选 FS。',
 trap:'Melihat kata nama “kabinet” lalu memilih FN.',
 keywords:['di dalam','lokasi']
},
{
 id:'PA-005',cat:'Pola Ayat',skill:'Membezakan frasa sendi dalam subjek',difficulty:'Sukar',
 q:'Pelajar dari kelas 2 Amanah itu sangat rajin.',
 i:'Tentukan pola ayat dasar.',
 a:['FN + FN','FN + FK','FN + FA','FN + FS'],c:2,
 e:'“Dari kelas 2 Amanah itu” masih sebahagian subjek. Predikat sebenar ialah “sangat rajin”, iaitu frasa adjektif.',
 cn:'“来自2 Amanah班的学生”整体是主语；真正谓语是“非常勤劳”，所以是 FN + FA。',
 formula:'Tentukan sempadan subjek dahulu sebelum melihat pola.',
 mnemonic:'先分主谓，再看谓语；不要看到 dari 就选 FS。',
 trap:'Nampak “dari” dalam subjek lalu memilih FN + FS.',
 keywords:['dari kelas','sangat rajin']
},
{
 id:'PA-006',cat:'Pola Ayat',skill:'FN + FN dengan jawatan',difficulty:'Sederhana Tinggi',
 q:'Wanita yang memakai kot putih itu pegawai perubatan daerah.',
 i:'Pilih pola ayat yang betul.',
 a:['FN + FN','FN + FK','FN + FA','FN + FS'],c:0,
 e:'Predikat “pegawai perubatan daerah” ialah nama jawatan, maka frasa nama.',
 cn:'谓语“地区医务官”是职位名称，因此属于 FN。',
 formula:'Jawatan, identiti atau hubungan = FN.',
 mnemonic:'说明是谁、什么身份＝FN。',
 trap:'Menganggap “memakai” menentukan pola walaupun berada dalam subjek.',
 keywords:['pegawai perubatan','identiti']
},
{
 id:'PA-007',cat:'Pola Ayat',skill:'FN + FK dengan objek',difficulty:'Sukar',
 q:'Pasukan penyelamat sedang mencari dua orang pendaki yang hilang.',
 i:'Tentukan pola ayat dasar.',
 a:['FN + FN','FN + FK','FN + FA','FN + FS'],c:1,
 e:'Inti predikat ialah kata kerja transitif “mencari”, diikuti objek.',
 cn:'谓语核心是及物动词“寻找”，后面有宾语，所以是 FN + FK。',
 formula:'Kata kerja + objek = FK.',
 mnemonic:'有动作，后面还有承受动作的对象＝FK。',
 trap:'Menganggap frasa panjang selepas kata kerja sebagai FN.',
 keywords:['mencari','dua orang pendaki']
},
{
 id:'PA-008',cat:'Pola Ayat',skill:'FN + FS sebagai tujuan',difficulty:'Sukar',
 q:'Hadiah utama pertandingan itu untuk pemenang kategori terbuka.',
 i:'Pilih pola ayat dasar.',
 a:['FN + FN','FN + FK','FN + FA','FN + FS'],c:3,
 e:'Predikat bermula dengan kata sendi “untuk”, maka frasa sendi nama.',
 cn:'谓语以介词“untuk”开头，所以属于 FS，不是 FN。',
 formula:'Untuk + frasa nama = FS.',
 mnemonic:'谓语以 untuk 开头，直接检查 FS。',
 trap:'Melihat “pemenang” sebagai kata nama lalu memilih FN.',
 keywords:['untuk pemenang','kata sendi']
},
{
 id:'PA-009',cat:'Pola Ayat',skill:'FN + FA dengan kata bantu darjah',difficulty:'Sukar',
 q:'Keadaan jalan menuju ke perkampungan itu semakin berbahaya.',
 i:'Tentukan pola ayat dasar.',
 a:['FN + FN','FN + FK','FN + FA','FN + FS'],c:2,
 e:'Predikat “semakin berbahaya” menyatakan sifat keadaan jalan.',
 cn:'“越来越危险”描述道路状况的性质，所以是 FA。',
 formula:'Semakin + kata sifat = FA.',
 mnemonic:'越来越＋性质＝FA。',
 trap:'Menganggap awalan “ber-” sentiasa kata kerja.',
 keywords:['semakin','berbahaya']
},
{
 id:'PA-010',cat:'Pola Ayat',skill:'FN + FK dalam ayat pasif',difficulty:'Sukar',
 q:'Bangunan bersejarah itu telah dipulihkan oleh pihak berkuasa tempatan.',
 i:'Pilih pola ayat dasar.',
 a:['FN + FN','FN + FK','FN + FA','FN + FS'],c:1,
 e:'Predikat “telah dipulihkan oleh pihak berkuasa tempatan” berinti kata kerja pasif “dipulihkan”.',
 cn:'谓语核心是被动动词“被修复”，仍属于 Frasa Kerja。',
 formula:'Kata kerja pasif di- tetap FK.',
 mnemonic:'被动动词也是动词，所以仍选 FK。',
 trap:'Menganggap semua ayat pasif mempunyai pola khas.',
 keywords:['telah dipulihkan','kata kerja pasif']
},
{
 id:'PA-011',cat:'Pola Ayat',skill:'FN + FN dengan frasa nama kompleks',difficulty:'Sukar',
 q:'Pemenang pertandingan pidato peringkat negeri itu anak sulung guru disiplin kami.',
 i:'Tentukan pola ayat dasar.',
 a:['FN + FN','FN + FK','FN + FA','FN + FS'],c:0,
 e:'Predikat “anak sulung guru disiplin kami” ialah frasa nama yang menyatakan hubungan.',
 cn:'谓语是在说明人物关系“是纪律老师的长子”，属于 FN。',
 formula:'Hubungan kekeluargaan = FN.',
 mnemonic:'说明“是谁的什么人”＝FN。',
 trap:'Menganggap “sulung” sahaja sebagai adjektif lalu memilih FA.',
 keywords:['anak sulung','hubungan']
},
{
 id:'PA-012',cat:'Pola Ayat',skill:'FN + FS sebagai arah',difficulty:'Sederhana Tinggi',
 q:'Rombongan pelajar itu ke Melaka pada minggu hadapan.',
 i:'Pilih pola ayat dasar.',
 a:['FN + FN','FN + FK','FN + FA','FN + FS'],c:3,
 e:'Predikat “ke Melaka pada minggu hadapan” bermula dengan kata sendi arah “ke”.',
 cn:'谓语以方向介词“ke”开头，所以是 FS。',
 formula:'Ke + tempat/arah = FS.',
 mnemonic:'去哪里，以 ke 开头＝FS。',
 trap:'Menyangka ada kata kerja “pergi” yang tersembunyi lalu memilih FK.',
 keywords:['ke Melaka','arah']
},
{
 id:'PA-013',cat:'Pola Ayat',skill:'FN + FA dengan kata nafi',difficulty:'Sukar',
 q:'Keputusan pertandingan itu tidak memuaskan.',
 i:'Tentukan pola ayat dasar.',
 a:['FN + FN','FN + FK','FN + FA','FN + FS'],c:2,
 e:'“Memuaskan” dalam ayat ini menerangkan sifat keputusan dan didahului kata nafi “tidak”.',
 cn:'这里“令人满意”是在描述结果的性质，前面有“tidak”，所以归入 FA。',
 formula:'Tidak + sifat = FA; bukan + nama = FN.',
 mnemonic:'tidak 常跟性质，bukan 常否定名词。',
 trap:'Menganggap semua perkataan berawalan meN- sebagai kata kerja.',
 keywords:['tidak memuaskan','sifat']
},
{
 id:'PA-014',cat:'Pola Ayat',skill:'FN + FK dengan komplemen',difficulty:'Sukar',
 q:'Adik saya bercita-cita untuk menjadi seorang jurutera aeroangkasa.',
 i:'Pilih pola ayat dasar.',
 a:['FN + FN','FN + FK','FN + FA','FN + FS'],c:1,
 e:'Predikat berinti kata kerja “bercita-cita”. Frasa selepasnya melengkapkan maksud kata kerja.',
 cn:'谓语核心是动作/状态动词“立志”，后面的内容只是补足它，因此是 FK。',
 formula:'Cari inti pertama predikat; unsur selepasnya mungkin hanya pelengkap.',
 mnemonic:'先找谓语第一个核心词；核心是动词就选 FK。',
 trap:'Melihat “seorang jurutera” lalu memilih FN.',
 keywords:['bercita-cita','menjadi']
},
{
 id:'PA-015',cat:'Pola Ayat',skill:'Analisis pola campuran',difficulty:'Sangat Sukar',
 q:'Kawasan rekreasi yang terletak di pinggir bandar itu masih menjadi pilihan utama para pengunjung.',
 i:'Tentukan pola ayat dasar yang paling tepat.',
 a:['FN + FN','FN + FK','FN + FA','FN + FS'],c:1,
 e:'Predikat bermula dengan kata bantu “masih” dan berinti kata kerja “menjadi”. Oleh itu, polanya FN + FK.',
 cn:'谓语核心是动词“menjadi（成为）”，虽然后面出现名词“pilihan utama”，整体仍是 FK。',
 formula:'Kata kerja “menjadi” menentukan pola FK walaupun diikuti frasa nama.',
 mnemonic:'看到 menjadi，先锁定动词核心＝FK。',
 trap:'Tertarik oleh frasa nama “pilihan utama” lalu memilih FN + FN.',
 keywords:['masih menjadi','pilihan utama']
}
];